const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const context={localStorage:{getItem:()=>null,setItem:()=>{}},console};
vm.createContext(context);
const source=fs.readFileSync(__dirname+'/app.js','utf8').split("document.addEventListener('click'")[0];
vm.runInContext(source,context);
let count=0;
function check(name,code){vm.runInContext(code,context);count++;console.log('PASS '+name)}
context.assert=assert;
check('40 demo records and valid backup',`var sample=demoData();assert.equal(sample.records.length,40);validateBackup(sample);`);
check('JSON round trip',`assert.equal(JSON.stringify(validateBackup(JSON.parse(JSON.stringify(sample)))),JSON.stringify(sample));`);
check('Reject invalid backup and duplicate IDs',`assert.throws(()=>validateBackup({version:1}));var bad=JSON.parse(JSON.stringify(sample));bad.records[1].id=bad.records[0].id;assert.throws(()=>validateBackup(bad));`);
check('Exact repeat boundary, same service, code normalization',`var base={...sample.records[0],id:1,code:' ШК-01 ',registered:'2025-01-01T08:00',restored:'2025-01-01T10:00',status:'Устранено'};var second={...base,id:2,code:'шк-01',registered:'2025-01-31T10:00',restored:'',status:'В работе'};assert.equal(repeats([second,base],30).has(2),true);assert.equal(repeats([base,{...second,registered:'2025-01-31T10:01'}],30).size,0);assert.equal(repeats([base,{...second,service:'Другая услуга'}],30).size,0);`);
check('No repeat without code or before restoration',`assert.equal(repeats([{...base,code:''},{...second,code:''}],30).size,0);assert.equal(repeats([{...base,restored:'2025-02-01T10:00'},second],30).size,0);`);
check('One repeat despite multiple previous records',`assert.equal(repeats([base,{...base,id:3},second],30).size,1);`);
check('Repeat outside report period still counts',`db={...sample,records:[base,second]};filters={period:'custom',from:'2025-01-31',to:'2025-01-31',town:'',service:'',cause:'',worker:'',status:''};assert.equal(selected().length,1);assert.equal(metrics(selected(),repeats(db.records,30)).repeat,1);`);
check('Empty metrics and average only closed',`assert.equal(metrics([],new Set()).avg,null);assert.equal(metrics([base,second],new Set([2])).avg,7200000);assert.equal(metrics([base,second],new Set([2])).share,50);`);
check('Invalid dates and required restoration',`assert.ok(recordErrors({...base,restored:'2024-12-31T10:00'}).restored);assert.ok(recordErrors({...base,restored:''}).restored);assert.equal(validDateTime('2025-02-30T10:00'),false);assert.ok(recordErrors({...base,affected:'-2'}).affected);`);
check('CSV Cyrillic, delimiter, BOM and formula protection',`var csv=csvText([{...base,note:'=SUM(1;2)'}]);assert.equal(csv.charCodeAt(0),65279);assert.ok(csv.includes('Населённый пункт'));assert.ok(csv.includes(';'));assert.ok(csv.includes("'=SUM"));`);
check('All sections render with populated data',`db=sample;filters={period:'all',town:'',service:'',cause:'',worker:'',status:''};for(var f of [overview,journal,causes,repeatsPage,tasksPage,reports,settingsPage])assert.ok(f(selected()).length>0);`);
check('All sections render with empty data',`db={...defaults(),initialized:true};for(var f of [overview,journal,causes,repeatsPage,tasksPage,reports,settingsPage])assert.ok(f([]).length>0);`);
check('Stored text is escaped',`assert.equal(esc('<script>"&'), '&lt;script&gt;&quot;&amp;');`);
const saved=vm.runInContext('JSON.stringify(sample)',context);
const elements=new Map();
const boot={localStorage:{getItem:()=>saved},console,document:{addEventListener(){},getElementById(id){if(!elements.has(id))elements.set(id,{});return elements.get(id)}},window:{addEventListener(){}},location:{hash:'#overview'},setInterval(){}};
vm.createContext(boot);
vm.runInContext(fs.readFileSync(__dirname+'/app.js','utf8'),boot);
assert.equal(vm.runInContext('loadError',boot),'');
assert.equal(vm.runInContext('db.records.length',boot),40);
assert.ok(elements.get('main').innerHTML.includes('Демонстрационные данные'));
count++;console.log('PASS Full app reload preserves saved records');
console.log(count+' checks passed');
